src:
  dir: ./input

dest:
  dir: ./output/koboGlo
  filename: ${dir}.pdf

width: 758
height: 942
quality: 80
maxProcess: 0

filters:
  - name: changeLineSpace
    options:
      widthRatio: 758
      heightRatio: 942
      lineSpaceScale: 0.1
      minSpace: 1
      maxRemove: 9999
      threshold: 180
      emptyLineThreshold: 0.01
