src:
  dir: ./input

dest:
  dir: ./output/koboMini
  filename: ${baseFilename}.cbz

width: 600
height: 800
quality: 80
maxProcess: 0

filters:
  - name: changeLineSpace
    options:
      widthRatio: 600
      heightRatio: 800
      lineSpaceScale: 0.1
      minSpace: 1
      maxRemove: 9999
      threshold: 180
      emptyLineThreshold: 0.005
