src:
  dir: ./input

dest:
  dir: ./output/dx
  filename: ${baseFilename}.pdf

width: 783
height: 1135
quality: 80
showEdgePoint: true
maxProcess: 0

filters:
  - name: resize
    options:
      widthScale: 0.9
      heightScale: 1.0
      scaleCover: false
  - name: changeLineSpace
    options:
      widthRatio: 783
      heightRatio: 1135
      lineSpaceScale: 0.005
      minSpace: 1
      maxRemove: 9999
      threshold: 180
      emptyLineThreshold: 0.005
